---
title: "Data visualisation"
author : "Jeremy Wicquart"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: "cosmo"
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 4
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Load packages

```{r base}

# 1. Source functions ----

source("functions/graphical_par.R")
source("functions/theme_map.R")
source("functions/theme_graph.R")

# 2. Required packages ----

library(tidyverse)
library(magrittr)
library(sf)
library(ggtext) # For element_markdown
library(patchwork)
sf_use_s2(FALSE) # Switch from S2 to GEOS

```

# Load data

```{r}

# 1. Load and transform data ----

# 1.1 SST anomaly data --

load("../data/sst_anomaly.RData")

data_sst_anom <- data_sst_anom %>% 
  drop_na(sst_anomaly_mean) %>% 
  filter(date < as.Date("2020-01-01")) %>% 
  mutate(sst_anomaly_type = ifelse(sst_anomaly_mean > 0,"#ec644b", "#59abe3"))

# 1.2 Add number of sites per GCRMN region --

load("../data/site_coordinates.RData")

data_sst_anom <- data_benthos %>% 
  st_drop_geometry() %>% 
  group_by(gcrmn_region) %>% 
  count() %>% 
  mutate(n = as.character(n),
         n = ifelse(nchar(n) == 4, paste0(substr(n, 1, 1), ",", substr(n, 2, 4)), n)) %>% 
  ungroup() %>% 
  left_join(data_sst_anom, .) %>% 
  mutate(gcrmn_region = paste0(gcrmn_region, " (n = ", n, ")"))

```

# Figure 1 - A

```{r}

# 1. Make the plot ----

plot_b <- ggplot(data = data_sst_anom %>% filter(gcrmn_region == "East Asia (n = 2,877)"), 
                 aes(x = date, y = sst_anomaly_mean)) +
  geom_ribbon(aes(ymin = 0, ymax = sst_anomaly_mean, fill = sst_anomaly_type)) +
  geom_path() +
  theme_graph() +
  theme(strip.background = element_blank(),
        strip.text = element_text(hjust = 0, size = 12)) +
  labs(x = "Year", y = "SST anomaly (°C)", title = "B. East Asia SST anomaly") +
  lims(y = c(-0.5, 0.7), x = c(as.Date("1985-01-01"), as.Date("2020-01-01"))) +
  scale_fill_identity()

```

# Figure 1 - B

```{r}

# 1. Transform the data ----

data_sst_anom <- data_sst_anom %>% 
  group_by(date) %>% 
  summarise(sst_anomaly_mean = mean(sst_anomaly_mean)) %>% 
  ungroup() %>% 
  mutate(sst_anomaly_type = ifelse(sst_anomaly_mean > 0,"#ec644b", "#59abe3"))

# 2. Make the plot ----

plot_a <- ggplot(data = data_sst_anom, aes(x = date, y = sst_anomaly_mean)) +
  geom_ribbon(aes(ymin = 0, ymax = sst_anomaly_mean, fill = sst_anomaly_type)) +
  geom_path() +
  theme_graph() +
  labs(x = "Year", 
       y = "SST anomaly (°C)", 
       title = "A. Global SST anomaly") +
  lims(y = c(-0.5, 0.7), x = c(as.Date("1985-01-01"), as.Date("2020-01-01"))) +
  scale_fill_identity()

```

# Combine plots

```{r}

# 1. Combine plots ----

plot_a + plot_b + plot_layout(ncol = 1)

# 2. Save the figure ----

ggsave("../figs/figure-2.png", height = 6, width = 5, dpi = 600)

```

# Reproducibility

```{r reprod}

# 1. Reproducibility ----

sessionInfo()

```

---
Jeremy WICQUART | jeremywicquart@gmail.com | `r format(Sys.time())`